# Generated by Django 5.1.4 on 2025-01-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='versemetric',
            name='size',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
