# Generated by Django 5.1.4 on 2025-02-25 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_norule'),
    ]

    operations = [
        migrations.CreateModel(
            name='StropheMetric',
            fields=[
                ('rule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poems.rule')),
                ('size', models.PositiveSmallIntegerField(default=0)),
            ],
            bases=('poems.rule',),
        ),
    ]
