# Generated by Django 5.1.4 on 2025-02-25 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_strophemetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sonnet',
            fields=[
                ('poemtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poems.poemtype')),
            ],
            bases=('poems.poemtype',),
        ),
    ]
