# Generated by Django 5.1.4 on 2025-02-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0005_sonnet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreePoem',
        ),
        migrations.DeleteModel(
            name='Sonnet',
        ),
    ]
