# Generated by Django 5.1.4 on 2025-02-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0006_remove_sonnet_poemtype_ptr_delete_freepoem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strophemetric',
            name='verses_per_strophe',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='versemetric',
            name='total_verses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
