# Generated by Django 5.1.4 on 2025-02-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0007_strophemetric_verses_per_strophe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strophemetric',
            name='verses_per_strophe',
            field=models.JSONField(),
        ),
    ]
